### ISSUE TITLE
customtkinter.CTkLabel ‘text_font’ need replace to ‘font’

### ISSUE THREAD

**Issue by telenkor** [Dreams005/RetroTechCollector#1]
Thanks for your development. As a beginner, it is very useful for me to study your solution.
I encountered a problem upon startup.
This may be due to some updates in the Customtkinter code that have occurred since your release.
As of the beginning of 2024, you should replace `text_font=` with `font=` everywhere in the `customtkinter.CTkLabel `parameters.

**Comment by Dreams005** [comment]
Hello, thank you very much for taking your time to look at my code.

> This may be due to some updates in the Customtkinter code that have occurred since your release.
This could very much be the case as it has been quite some time since this program was made, I will have a look at it.

Once again, thank you for bringing this to my attention. :)

**Comment by Dreams005** [comment]
fixed in v1.11 :)
